old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        user_lecture_point_sum:
            connection: default
            exchange_options: { name: 'old_sound_rabbit_mq.user_lecture_point_sum', type: direct }

    consumers:
        user_lecture_point_sum:
            connection: default
            exchange_options: {name: 'old_sound_rabbit_mq.user_lecture_point_sum', type: direct}
            queue_options: {name: 'old_sound_rabbit_mq.consumer.user_lecture_point_sum'}
            callback: App\Controller\Amqp\UserSumLecturePoint\Consumer
            idle_timeout: 300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout: 1800
                exit_code: 0
            qos_options: {prefetch_size: 0, prefetch_count: 30, global: false}