<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250724083414 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE course_user_point (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id BIGINT NOT NULL, course_id BIGINT NOT NULL, sum_course_point INT DEFAULT NULL, is_verified SMALLINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX course_user_point__user_id__idx ON course_user_point (user_id)');
        $this->addSql('CREATE INDEX course_user_point__course_id__idx ON course_user_point (course_id)');
        $this->addSql('ALTER TABLE course_user_point ADD CONSTRAINT course_user_point__user_id__fk FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE course_user_point ADD CONSTRAINT course_user_point__course_id__fk FOREIGN KEY (course_id) REFERENCES course (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE course_user_point DROP CONSTRAINT course_user_point__user_id__fk');
        $this->addSql('ALTER TABLE course_user_point DROP CONSTRAINT course_user_point__course_id__fk');
        $this->addSql('DROP TABLE course_user_point');
    }
}
