<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250724074948 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE lecture_user_point (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id BIGINT NOT NULL, lecture_id BIGINT NOT NULL, sum_lecture_point INT DEFAULT NULL, is_verified SMALLINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX lecture_user_point__user_id__idx ON lecture_user_point (user_id)');
        $this->addSql('CREATE INDEX lecture_user_point__lecture_id__idx ON lecture_user_point (lecture_id)');
        $this->addSql('ALTER TABLE lecture_user_point ADD CONSTRAINT lecture_user_point__user_id__fk FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lecture_user_point ADD CONSTRAINT lecture_user_point__lecture_id__fk FOREIGN KEY (lecture_id) REFERENCES lecture (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE lecture_user_point DROP CONSTRAINT lecture_user_point__user_id__fk');
        $this->addSql('ALTER TABLE lecture_user_point DROP CONSTRAINT lecture_user_point__lecture_id__fk');
        $this->addSql('DROP TABLE lecture_user_point');
    }
}
