controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

hello_world:
    path: /world/hello
    controller: App\Controller\WorldController::hello

create_user:
    path: /create/user
    controller: App\Controller\UserController::createUser